public enum ErrorType {
    VAR_UNDEF,
    FUNC_UNDEF,
    REDEF_VAR,
    REDEF_FUNC,
    SIGN_DISMATCH,
    OP_DISMATCH,
    FUNR_DISMATCH,
    PARAM_NOT_APPLICABLE,
    INDEX_ON_NON_ARRAY,
    FUNC_CALL_ON_VARIABLE,
    SIGN_ON_FUNC
}
